version: '3'

services:
  postgres:
    image: postgres:alpine
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: avlist
      POSTGRES_PASSWORD: AVLIST
      POSTGRES_DB: avlist-test
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '36379:6379'
    depends_on:
      - postgres
    volumes:
      - redis_data:/data

  localstack:
    image: localstack/localstack
    ports:
      - '34566:4566'
    environment:
      SERVICES: s3
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
    volumes:
      - localstack_data:/tmp/localstack
      - ./scripts/aws:/docker-entrypoint-initaws.d

volumes:
  postgres_data:
  redis_data:
  localstack_data:
