version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_URL: ${DB_URL}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET__ASSET__NAME: ${AWS_S3_BUCKET__ASSET__NAME}
  postgres:
    image: postgres:alpine
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./.dev/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: javlist

  localstack:
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566'
    environment:
      SERVICES: s3
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
    volumes:
      - ./.dev/localstack:/tmp/localstack
      - ./scripts/aws:/docker-entrypoint-initaws.d

  redis:
    image: redis:alpine
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ./.dev/redis:/data
