version: '3'

services:
  postgres:
    image: postgres:alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  redis:
    image: redis:alpine
    expose:
      - 6379
    depends_on:
      - postgres
