name: Test, build and publish packages

permissions:
  contents: read
  packages: write

concurrency:
  group: publish-${{ github.event_name }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:


jobs:
  test:
    name: Run test
    uses: pukenicorn/gh-workflows/.github/workflows/test.yml@main
    with:
      language: node
      registry: https://npm.pkg.github.com

  publish-docker:
    name: Build and publish docker image
    needs: [ test ]
    uses: pukenicorn/gh-workflows/.github/workflows/publish-docker.yml@main
    with:
      registry: ghcr.io
      ignore-file-changes: ${{ (github.event_name == 'release' && github.event.action == 'published') || github.event_name == 'workflow_dispatch' }}
    secrets:
      REGISTRY_USERNAME: ${{ github.actor }}
      BUILD_ARGS: |
        SUKEBEI_PKG_TOKEN=${{ secrets.PKG_TOKEN || github.token }}
