name: Test, build and publish packages

permissions:
  contents: read
  packages: write

concurrency:
  group: publish-${{ github.event_name }}
  cancel-in-progress: true

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      version:
        description: Version to the publish package
        type: string
        required: true


jobs:
  test:
    name: Run test
    uses: pukenicorn/gh-workflows/.github/workflows/test.yml@main
    with:
      language: node
      registry: https://npm.pkg.github.com

  publish-docker:
    name: Build and publish docker image
    needs: [ test ]
    uses: pukenicorn/gh-workflows/.github/workflows/publish-docker.yml@main
    with:
      registry: ghcr.io
      ignore-file-changes: ${{ (github.event_name == 'release' && github.event.action == 'published') || github.event_name == 'workflow_dispatch' }}
    secrets:
      REGISTRY_USERNAME: ${{ github.actor }}
      BUILD_ARGS: |
        SUKEBEI_PKG_TOKEN=${{ secrets.PKG_TOKEN || github.token }}

  publish-client-ts-axios:
    name: Build and publish typescript axios client
    needs: [ test ]
    uses: pukenicorn/gh-workflows/.github/workflows/publish-pkg.yml@main
    with:
      base-language: node
      package-path: ./generated
      post-setup-command: generate:spec
      package-name: "@${{ github.repository }}-client"
      package-registry: https://npm.pkg.github.com
      package-version: ${{ github.event.release.tag_name || inputs.version }}
    if: github.event_name == 'release' && github.event.action == 'published'

  publish-client-cs-netcore:
    name: Build and publish c# netcore client
    needs: [ test ]
    uses: pukenicorn/gh-workflows/.github/workflows/publish-pkg.yml@main
    with:
      base-language: node
      package-language: dotnet
      package-language-cache: none
      package-path: ./generated
      post-setup-command: generate:spec
      package-name: Pukenicorn.Sukebei.JavList.Client
      package-registry: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      package-version: ${{ github.event.release.tag_name || inputs.version }}
    if: github.event_name == 'release' && github.event.action == 'published'

  publish-client-dart:
    name: Build and publish dart client
    needs: [ test ]
    uses: pukenicorn/gh-workflows/.github/workflows/publish-pkg.yml@main
    with:
      base-language: node
      package-language: dart
      package-language-cache: none
      package-path: ./generated
      post-setup-command: generate:spec
      package-name: "javlist_client"
      package-version: ${{ github.event.release.tag_name || inputs.version }}
    if: github.event_name == 'release' && github.event.action == 'published'
