name: Test and check for dependabot

permissions:
  pull-requests: write
  contents: write
  packages: read

concurrency:
  group: pr-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      pr-number:
        description: ID of PR to be run against
        type: string
        required: true


jobs:
  test:
    uses: pukenicorn/gh-workflows/.github/workflows/test.yml@main
    with:
      language: node
      registry: https://npm.pkg.github.com

  dependabot:
    needs: [ test ]
    uses: pukenicorn/gh-workflows/.github/workflows/dependabot.yml@main
    with:
      pr-number: ${{ inputs.pr_number || 0 }}
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
